// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbXNpZZ1-MiNnMPHuaSU_Et9JPq2w0Oto',
    appId: '1:505261881210:web:c428813afcad0b61b488c3',
    messagingSenderId: '505261881210',
    projectId: 'heritage-vista',
    authDomain: 'heritage-vista.firebaseapp.com',
    storageBucket: 'heritage-vista.appspot.com',
    measurementId: 'G-2BYF5W1HM6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYkvZx1fyAwiaOVp6bboDDBBRADADmsGs',
    appId: '1:505261881210:android:20af7080ebee1bd9b488c3',
    messagingSenderId: '505261881210',
    projectId: 'heritage-vista',
    storageBucket: 'heritage-vista.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjC_uwOjOCE3FbX0EYtIDstFlgTyrclzA',
    appId: '1:505261881210:ios:c2cf6095735ef91ab488c3',
    messagingSenderId: '505261881210',
    projectId: 'heritage-vista',
    storageBucket: 'heritage-vista.appspot.com',
    iosBundleId: 'com.example.heritageVista',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjC_uwOjOCE3FbX0EYtIDstFlgTyrclzA',
    appId: '1:505261881210:ios:bcf86cdad756a535b488c3',
    messagingSenderId: '505261881210',
    projectId: 'heritage-vista',
    storageBucket: 'heritage-vista.appspot.com',
    iosBundleId: 'com.example.heritageVista.RunnerTests',
  );
}
